stages:
  - test
  - build

unit_tests:
  stage: test
  image: python:3.10
  script:
    - pip install -r backend/requirements.txt
    - python -m backend.chat.unittest
    - python -m backend.topic.unittest
  only:
    - main
    - ci/cd

docker_build:
  stage: build
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t git.sjtu.edu.cn:5050/max_planck/nis3366web .
    - docker push git.sjtu.edu.cn:5050/max_planck/nis3366web
  only:
    - main
    - ci/cd

