name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitLab Container Registry
        run: |
          echo "${{ secrets.GITLAB_REGISTRY_PASSWORD }}" | docker login git.sjtu.edu.cn:5050 -u "${{ secrets.GITLAB_REGISTRY_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t git.sjtu.edu.cn:5050/max_planck/nis3366web .

      - name: Push Docker image
        run: |
          docker push git.sjtu.edu.cn:5050/max_planck/nis3366web
